### ISSUE TITLE
Camera pose?

### ISSUE THREAD

**Issue by naoto0804** [ai4ce/SPARE3D#2]
Thank you for releasing such a nice dataset.
Just from curiosity, can we use the camera pose of each image relative to the world coordinate, for this task?

**Comment by simbaforrest** [comment]
Thanks for your interest.

If you mean to solve the Isometric to Pose task or the Pose to Isometric task, our only input are the line drawing images. For the Pose to Isometric task, we provide a one-hot encoding to represent one of the 8 poses. 

Of course, you can convert the one-hot encoding representation to the actual camera orientation matrix for generating the isometric line drawing from the 3D model (and we only use orthographic projection so the position portion of the pose matrix doesn't matter), but since the 3D model is never available during the reasoning, we do not see how using the actual orientation matrix is useful.

Does this answer your question?

**Comment by simbaforrest** [comment]
If it answers the question, please consider closing this issue. Thank you. @naoto0804

**Comment by naoto0804** [comment]
Thanks!
